#!/bin/bash
pid_file="./../runtime/app.pid"
if [ -f "$pid_file" ]; then
    pid=$(cat $pid_file)
    if [ -n "$pid" ]; then
        echo "kill $pid"
        kill  $pid
    fi
else
    echo "no pid file"
    ./../bin/app&
fi