info:
  contact: {}
  license: {}
paths:
  /api/v1/create_account:
    post:
      parameters:
      - description: 用户名
        in: body
        name: username
        required: true
        schema:
          type: string
      - description: 密码
        in: body
        name: password
        required: true
        schema:
          type: string
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":"ok","msg":"ok"}'
          schema:
            type: string
      summary: 创建账号
  /auth:
    post:
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{"token":"", "user":"","expire":""},"msg":"ok"}'
          schema:
            type: string
      summary: 获取认证
swagger: "2.0"
